
export const BACKEND_LOGIN = "BACKEND_LOGIN"
export const BACKEND_LOGOUT = "BACKEND_LOGOUT"
export const BACKEND_ERROR = "BACKEND_ERROR"

export const UPDATE_BOARD = "UPDATE_BOARD"
export const UPDATE_NODE = "UPDATE_NODE"
export const REMOVE_NODE = "REMOVE_NODE"
