
export const BACKEND_LOGIN = "BACKEND_LOGIN";
export const BACKEND_LOGOUT = "BACKEND_LOGOUT";
export const BACKEND_ERROR = "BACKEND_ERROR";

export const LIST_UPDATE = "LIST_UPDATE";
export const LIST_REMOVE = "LIST_REMOVE";

export const UPDATE_BOARD = "UPDATE_BOARD";
export const REMOVE_BOARD = "REMOVE_BOARD";

export const UPDATE_OBJECT = "UPDATE_OBJECT";
export const REMOVE_OBJECT = "REMOVE_OBJECT";