
export const MINDMAP_PIN_RADIUS = 10;
export const MINDMAP_NODE_RADIUS = 30;
export const MINDMAP_NODE_HIGHLIGHT_MARGIN = 8;
export const MINDMAP_MODE_DEFAULT = "MINDMAP_MODE_DEFAULT";
export const MINDMAP_MODE_LINE_EDIT = "MINDMAP_MODE_LINE_EDIT";

export const LONGPRESS_TIMEOUT = 0.5;
export const PRESS_DELTA_THRESHOLD = 10; // pixels
