
export const MINDMAP_PIN_RADIUS = 10;
export const MINDMAP_NODE_RADIUS = 40;
export const MINDMAP_NODE_HIGHLIGHT_MARGIN = 8;
export const MINDMAP_MODE_DEFAULT = "MINDMAP_MODE_DEFAULT";
export const MINDMAP_MODE_LINE_EDIT = "MINDMAP_MODE_LINE_EDIT";
